export enum SECTION {
  MATERNEL = "MATERNEL",
  PRIMAIRE = "PRIMAIRE",
  SECONDAIRE = "SECONDAIRE",
}

export enum USER_ROLE {
  PERSONNEL = "PERSONNEL",
  PROMOTEUR = "PROMOTEUR",
  ADMIN = "ADMINISTRATEUR",
  ELEVE = "ELEVE",
}
