name: Continuous Integration (Triage)

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  triage:
    name: Verify Integrity and Linting
    runs-on: ubuntu-latest
    outputs:
      markdown_change: ${{ steps.filter_markdown.outputs.change }}
      markdown_files: ${{ steps.filter_markdown.outputs.change_files }}

    steps:
      - name: Scan Restricted File Changes
        uses: dorny/paths-filter@v3
        id: filter_restricted
        with:
          list-files: json
          filters: |
            change:
              - 'package-lock.json'
              - 'yarn.lock'
              - 'pnpm-lock.yaml'

      - name: Enforce Contribution Policy
        if: steps.filter_restricted.outputs.change == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const badFiles = ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'].join('\n- ');
            const reviewMessage = `👋 Hello! It looks like your contribution contains modifications to restricted ecosystem lockfiles:\n- ${badFiles}\n\nTo proceed, please revert these changes locally using \`git checkout origin/main <file_name>\` and update your Pull Request. Thank you! :octocat:`;

            let workflowFailMessage = "Forbidden file modifications detected in the lockfiles.";
            try {
              const createdComment = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: reviewMessage,
              });
              workflowFailMessage += ` Please refer to ${createdComment.data.html_url} for context.`;
            } catch(err) {
              console.error("Failed to append dynamic PR comment.", err);
            }
            core.setFailed(workflowFailMessage);

      - name: Filter Markdown Assets
        if: always()
        uses: dorny/paths-filter@v3
        id: filter_markdown
        with:
          list-files: shell
          filters: |
            change:
              - added|modified: '*.md'

  lint-markdown:
    name: Quality Assurance (Markdown)
    runs-on: ubuntu-latest
    needs: triage
    if: always() && needs.triage.outputs.markdown_change == 'true'
    steps:
      - name: Checkout Target Payload
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Lint Documentation Standard
        run: npx markdownlint-cli ${{ needs.triage.outputs.markdown_files }} --ignore node_modules
