name: Automated Release

on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - name: Execute Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          # Utilisation du PAT pour permettre le trigger automatique du build
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
