name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies

        # run: npm ci
        run: npm install --legacy-peer-deps

      - name: Get next version and update app.json
        id: get_version
        run: |
          # Determine the next version (this is a heuristic, semantic-release will confirm)
          # For more accuracy, you might run semantic-release dry-run first
          # However, for simply updating app.json based on what semantic-release _will_ set
          # in package.json, this is usually sufficient.
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
